pragma circom 2.2.3;
include "snapshot-hash-core.circom";
include "income-activity-core.circom";
include "history-core.circom";

// Local combined prototype. Uses existing PROVISIONAL commitment tags/order.
// Reveals three computed bits and context digest; no private roots or counts.
// PROVISIONAL v0.2. Signatures and current-chain authorization are external.
template EligibilityV02() {
    signal input expectedCommitment;
    signal input passportId;
    signal input holderBinding;
    signal input evidenceUpdatedAt;
    signal input evidenceVersion;
    signal input verifierId;
    signal input chainId;
    signal input consumer;
    signal input requestHi;
    signal input requestLo;
    signal input policyHi;
    signal input policyLo;
    signal input domainHi;
    signal input domainLo;
    signal input expiresAt;
    signal input maxEvidenceAgeDays;
    signal input incomeEnabled;
    signal input incomeWindowMonths;
    signal input minAverageIncomePaise;
    signal input activityEnabled;
    signal input activityIsWeekly;
    signal input activityWindow;
    signal input minActivePeriods;
    signal input historyEnabled;
    signal input minHistoryMonths;
    signal input evidenceProviderId;
    signal input evidenceDataHash;
    signal input verifiedHistoryStartDate;
    signal input sourceDirectoryVersion;
    signal input monthlyGigIncomeTotals[36];
    signal input weeklyActivity[156];
    signal input monthlyActivity[36];
    signal input cutoffYear;
    signal input cutoffMonth;
    signal input cutoffDay;
    signal input targetYear;
    signal input targetMonth;
    signal input targetDay;
    signal output incomePass;
    signal output historyPass;
    signal output activityPass;
    signal output authorizationBinding;
    component snapshot = ProvisionalSnapshotHash();
    snapshot.passportId <== passportId;
    snapshot.holderBinding <== holderBinding;
    snapshot.evidenceProviderId <== evidenceProviderId;
    snapshot.evidenceDataHash <== evidenceDataHash;
    snapshot.verifiedHistoryStartDate <== verifiedHistoryStartDate;
    snapshot.evidenceUpdatedAt <== evidenceUpdatedAt;
    snapshot.sourceDirectoryVersion <== sourceDirectoryVersion;
    snapshot.expectedCommitment <== expectedCommitment;
    component holderBits = Num2Bits(160);
    holderBits.in <== holderBinding;
    component predicates = IncomeActivity();
    for (var i=0; i<36; i++) {
        snapshot.monthlyGigIncomeTotals[i] <== monthlyGigIncomeTotals[i];
        snapshot.monthlyActivity[i] <== monthlyActivity[i];
        predicates.monthlyGigIncomeTotals[i] <== monthlyGigIncomeTotals[i];
        predicates.monthlyActivity[i] <== monthlyActivity[i];
    }
    for (var j=0; j<156; j++) {
        snapshot.weeklyActivity[j] <== weeklyActivity[j];
        predicates.weeklyActivity[j] <== weeklyActivity[j];
    }
    predicates.incomeEnabled <== incomeEnabled;
    predicates.incomeWindowMonths <== incomeWindowMonths;
    predicates.minAverageIncomePaise <== minAverageIncomePaise;
    predicates.activityEnabled <== activityEnabled;
    predicates.activityIsWeekly <== activityIsWeekly;
    predicates.activityWindow <== activityWindow;
    predicates.minActivePeriods <== minActivePeriods;
    component history = History();
    history.verifiedHistoryStartDate <== verifiedHistoryStartDate;
    history.evidenceUpdatedAt <== evidenceUpdatedAt;
    history.historyEnabled <== historyEnabled;
    history.minHistoryMonths <== minHistoryMonths;
    history.cutoffYear <== cutoffYear;
    history.cutoffMonth <== cutoffMonth;
    history.cutoffDay <== cutoffDay;
    history.targetYear <== targetYear;
    history.targetMonth <== targetMonth;
    history.targetDay <== targetDay;
    historyPass <== history.historyPass;
    component binding = Poseidon(16);
    binding.inputs[0] <== expectedCommitment;
    binding.inputs[1] <== passportId;
    binding.inputs[2] <== holderBinding;
    binding.inputs[3] <== evidenceUpdatedAt;
    binding.inputs[4] <== evidenceVersion;
    binding.inputs[5] <== verifierId;
    binding.inputs[6] <== chainId;
    binding.inputs[7] <== consumer;
    binding.inputs[8] <== requestHi;
    binding.inputs[9] <== requestLo;
    binding.inputs[10] <== policyHi;
    binding.inputs[11] <== policyLo;
    binding.inputs[12] <== domainHi;
    binding.inputs[13] <== domainLo;
    binding.inputs[14] <== expiresAt;
    binding.inputs[15] <== maxEvidenceAgeDays;
    authorizationBinding <== binding.out;
    component passportIdBits = Num2Bits(64); passportIdBits.in <== passportId;
    component evidenceVersionBits = Num2Bits(64); evidenceVersionBits.in <== evidenceVersion;
    component verifierIdBits = Num2Bits(160); verifierIdBits.in <== verifierId;
    component chainIdBits = Num2Bits(64); chainIdBits.in <== chainId;
    component consumerBits = Num2Bits(160); consumerBits.in <== consumer;
    component expiresAtBits = Num2Bits(40); expiresAtBits.in <== expiresAt;
    component maxEvidenceAgeDaysBits = Num2Bits(32); maxEvidenceAgeDaysBits.in <== maxEvidenceAgeDays;
    component requestHiBits = Num2Bits(128); requestHiBits.in <== requestHi;
    component requestLoBits = Num2Bits(128); requestLoBits.in <== requestLo;
    component policyHiBits = Num2Bits(128); policyHiBits.in <== policyHi;
    component policyLoBits = Num2Bits(128); policyLoBits.in <== policyLo;
    component domainHiBits = Num2Bits(128); domainHiBits.in <== domainHi;
    component domainLoBits = Num2Bits(128); domainLoBits.in <== domainLo;
    incomePass <== predicates.incomePass;
    activityPass <== predicates.activityPass;
}
component main {public [expectedCommitment, passportId, holderBinding, evidenceUpdatedAt, evidenceVersion, verifierId, chainId, consumer, requestHi, requestLo, policyHi, policyLo, domainHi, domainLo, expiresAt, maxEvidenceAgeDays, incomeEnabled, incomeWindowMonths, minAverageIncomePaise, activityEnabled, activityIsWeekly, activityWindow, minActivePeriods, historyEnabled, minHistoryMonths]} = EligibilityV02();
