'use client';
import {useEffect,useState} from 'react';
import {BrowserProvider,JsonRpcProvider,TypedDataEncoder,hexlify,toUtf8Bytes} from 'ethers';
import ApplicationQr from './ApplicationQr';
const personas=['RAMESH','SURESH','IMRAN','MANJUNATH','VENKATESH','FARHAN','ARJUN'];
async function call(action:string,p:any={}){const r=await fetch('/api/app/'+action,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});const v=await r.json();if(!r.ok)throw Error(v.error??'Request failed');return v;}
const date=(n:any)=>n?new Date(Number(n)*1000).toLocaleString():'—';
export default function ConnectedApplication(){
 const [b,B]=useState<any>(null),[d,D]=useState<any>(null),[wallet,W]=useState(''),[mode,M]=useState('local');
 const [busy,S]=useState('Starting local services…'),[error,E]=useState(''),[notice,N]=useState('');
 const [persona,P]=useState('RAMESH'),[phone,F]=useState('+919000000001'),[otp,O]=useState(''),[sid,I]=useState('');
 const [mailbox,setMailbox]=useState<{code:string;disclosure:string}|null>(null);
 const [pid,Q]=useState('1'),[consumer,C]=useState('loan'),[recovery,R]=useState(''),[replacement,J]=useState(''),[publicRecord,U]=useState<any>(null);
 const [income,A]=useState(false),[threshold,T]=useState('2000000'),[history,H]=useState(false),[months,K]=useState('12'),[activity,V]=useState(false),[active,X]=useState('9');
 useEffect(()=>{call('info').then(async v=>{B(v);W(v.devWallets.find((a:any)=>a.label==='Worker 2').address);const id=new URLSearchParams(location.search).get('passportId');if(id){Q(id);U(await call('publicPassport',{passportId:id}));}try{const current=await call('dashboard');D(current);W(current.wallet);M(v.devWallets.some((a:any)=>a.address.toLowerCase()===current.wallet.toLowerCase())?'local':'external');}catch{}}).catch(e=>E(e.message)).finally(()=>S(''));},[]);
 async function run(label:string,fn:()=>Promise<any>){S(label+'…');E('');N('');try{await fn();}catch(e:any){E(e.message);if(e.message==='AUTHENTICATION_REQUIRED')D(null);}finally{S('');}}
 async function refresh(){D(await call('dashboard'));}
 const button=(label:string,fn:()=>Promise<any>)=><button disabled={!!busy} onClick={()=>void run(label,fn)}>{label}</button>;
 const field=(label:string,value:string,set:(v:string)=>void)=><label style={{display:'block',margin:'12px 0'}}>{label} <input value={value} onChange={e=>set(e.target.value)}/></label>;
 const section=(title:string,children:React.ReactNode)=><section className="card" style={{padding:24}}><h2>{title}</h2>{children}</section>;
 async function provider(){if(mode==='local')return new JsonRpcProvider(b.rpcUrl,1337,{cacheTimeout:-1});if(!(window as any).ethereum)throw Error('No browser wallet found.');return new BrowserProvider((window as any).ethereum);}
 async function sign(a:any,message?:string){const p=await provider();const address=d?.wallet??wallet;try{
  if(mode==='local')return message?await p.send('eth_sign',[address,hexlify(toUtf8Bytes(message))]):await p.send('eth_signTypedData_v4',[address,TypedDataEncoder.getPayload(a.domain,a.types,a.value)]);
  const signer=await (p as BrowserProvider).getSigner(address);return message?await signer.signMessage(message):await signer.signTypedData(a.domain,a.types,a.value);
 }finally{if(mode==='local')p.destroy();}}
 async function connect(){let address=wallet;if(mode==='external'){const eth=(window as any).ethereum;if(!eth)throw Error('No browser wallet found.');address=(await eth.request({method:'eth_requestAccounts'}))[0];W(address);try{await eth.request({method:'wallet_switchEthereumChain',params:[{chainId:'0x539'}]});}catch{await eth.request({method:'wallet_addEthereumChain',params:[{chainId:'0x539',chainName:'GigVault local',nativeCurrency:{name:'Local ETH',symbol:'ETH',decimals:18},rpcUrls:[b.rpcUrl]}]});}}
  const a=await call('challenge',{wallet:address}),p=await provider();try{const signature=mode==='local'?await p.send('eth_signTypedData_v4',[address,TypedDataEncoder.getPayload(a.domain,a.types,a.value)]):await (await (p as BrowserProvider).getSigner(address)).signTypedData(a.domain,a.types,a.value);await call('login',{nonce:a.value.nonce,signature});await refresh();}finally{if(mode==='local')p.destroy();}}
 async function action(name:string,requestId?:string){const a=await call('actionChallenge',{action:name,requestId});if(!confirm(a.message+'\nSource: signed synthetic Mock FIP\nAccount: '+a.scope.account+'\nCutoff: '+date(a.scope.cutoff)))return false;await call('actionSubmit',{id:a.id,signature:await sign(null,a.message)});await refresh();return true;}
 async function send(tx:any,id?:string){const p=await provider();try{const signer=await (p as any).getSigner(d.wallet),sent=await signer.sendTransaction(tx),receipt=await sent.wait();await call('transactionMined',{hash:receipt.hash,id});await refresh();N('Confirmed local transaction: '+receipt.hash);}finally{if(mode==='local')p.destroy();}}
 async function start(){setMailbox(null);O('');I('');const a=await call('onboardStart',{recoveryIdentity:recovery||undefined});await call('onboardWallet',{sessionId:a.sessionId,signature:await sign(null,a.message)});I(a.sessionId);N('Wallet challenge accepted. Request your mock OTP below.');}
 async function policy(){const criteria={incomeEnabled:income?'1':'0',incomeWindowMonths:income?'6':'0',minAverageIncomePaise:income?threshold:'0',historyEnabled:history?'1':'0',minHistoryMonths:history?months:'0',activityEnabled:activity?'1':'0',activityIsWeekly:'0',activityWindow:activity?'12':'0',minActivePeriods:activity?active:'0',maxEvidenceAgeDays:'30'};const a=await call('policyPrepare',{passportId:pid,consumer,criteria});await call('policySubmit',{id:a.id,signature:await sign(a)});await refresh();}
 return <main className="wrap" style={{display:'grid',gap:24}}>
 {section('Your work. Your proof.',<><p>Connect your wallet, authorize your evidence and approve each eligibility request.</p><p>₹0 local environment · signed synthetic identity and Mock FIP · mock OTP mailbox, no SMS · actual EVM transactions and Groth16 verification. Real Aadhaar is unavailable.</p><p className="muted">Development wallets are unlocked on loopback. Use synthetic data only. State resets on server restart.</p>
 {busy&&<p role="status">{busy} Proof generation may take several minutes.</p>}{error&&<p role="alert" style={{color:'var(--bad)'}}>{error}</p>}{notice&&<p role="status" style={{overflowWrap:'anywhere'}}>{notice}</p>}
 {b&&<><label>Wallet mode <select disabled={!!d||!!busy} value={mode} onChange={e=>M(e.target.value)}><option value="local">Local development wallet</option><option value="external">Browser wallet</option></select></label>
 {mode==='local'&&<label>Wallet <select disabled={!!d||!!busy} value={wallet} onChange={e=>W(e.target.value)}>{b.devWallets.filter((a:any)=>!a.label.startsWith('Attester')).map((a:any)=><option key={a.address} value={a.address}>{a.label} · {a.address.slice(0,10)}</option>)}</select></label>}
 {!d?button('Connect and sign in',connect):<>{button('Refresh state',refresh)}{button('Disconnect',async()=>{await call('logout');D(null);I('');})}<p style={{overflowWrap:'anywhere'}}>Signed in as {d.role}: {d.wallet}</p></>}</>}
 </>)}
 {b&&section('Public passport lookup',<><p>Only the on-chain record is public. Financial summaries stay with the worker.</p>{field('Passport ID',pid,Q)}{button('Look up passport',async()=>U(await call('publicPassport',{passportId:pid})))}{publicRecord&&<p>#{publicRecord.passportId} · {publicRecord.status} · holder {publicRecord.holderWallet} · evidence v{publicRecord.evidenceVersion}</p>}</>)}
 {d?.role==='worker'&&!d.worker&&section('Synthetic onboarding',<><p>Choose a supplied test persona. The private Mock IDP signs its identity assertion. This is not a government credential.</p><label>Persona <select value={persona} onChange={e=>P(e.target.value)}>{personas.map(p=><option key={p}>{p}</option>)}</select></label>{field('Recovery identity (blank for first registration)',recovery,R)}{button('Start onboarding and sign wallet challenge',start)}
 {sid&&<>{field('Synthetic Indian phone',phone,F)}{button('Request mock OTP',async()=>{setMailbox(null);O('');await call('otpStart',{sessionId:sid,phone});N('Mock OTP created. Open your private local mailbox below. No SMS is sent.');})}{button('Open my local mock mailbox',async()=>{const v=await call('otpMailbox',{sessionId:sid});setMailbox(v);N('Your mock OTP is displayed below. Enter it in the OTP code field.');})}
 {mailbox&&<div role="status" aria-label="Local mock mailbox" style={{margin:'12px 0',padding:16,border:'1px solid var(--line)',borderRadius:12}}><p>{mailbox.disclosure}</p><p>Mock OTP: <strong style={{fontSize:24,letterSpacing:4}}>{mailbox.code}</strong></p></div>}
 {field('OTP code',otp,O)}{button('Verify mock OTP',async()=>{await call('otpVerify',{sessionId:sid,code:otp});setMailbox(null);O('');N('Mock OTP accepted. Continue with synthetic identity.');})}{button('Verify synthetic identity and bind wallet',async()=>{await call('identityCommit',{sessionId:sid,persona});I('');setMailbox(null);O('');await refresh();})}</>}
 {busy&&<p role="status">{busy}</p>}{error&&<p role="alert" style={{color:'var(--bad)'}}>{error}</p>}{notice&&<p role="status">{notice}</p>}
 </>)}
 {d?.worker&&section(d.worker.name+' · worker dashboard',<><p>Identity: {d.worker.trust} · protected phone {d.worker.phoneMasked}</p><p>FIP consent: {d.consent?.status??'Not granted'} {d.consent&&<>· expires {date(d.consent.expiresAt)}</>}</p>{button('Review and sign FIP consent',()=>action('CREATE_CONSENT'))}{d.consent&&button('Revoke FIP consent',async()=>{await call('revokeConsent');await refresh();})}{!d.passport&&button(d.reissueAllowed?'Reissue passport':'Mint passport',()=>action(d.reissueAllowed?'REISSUE_PASSPORT':'MINT_PASSPORT'))}
 {d.passport&&<><p>Passport #{d.passport.passportId} · {d.passport.status} · evidence version {d.passport.evidenceVersion} · schema {d.passport.schemaVersion}</p><p style={{overflowWrap:'anywhere'}}>Holder {d.passport.holderWallet}<br/>Commitment {d.passport.evidenceCommitment}<br/>Evidence cutoff {date(d.passport.evidenceUpdatedAt)}</p>{d.passport.status==='ACTIVE'&&button('Refresh signed evidence',async()=>{if(await action('CREATE_CONSENT'))await action('REFRESH_PASSPORT');})}<ApplicationQr path={'/?passportId='+d.passport.passportId} label='Share public passport link'/><p>Welfare lifetime claim: {d.identityState.claimed?'Claimed':'Not claimed'} · debt {Number(d.identityState.principal)/1e6} MockUSDC · wallet balance {Number(d.balanceMockUSDC)/1e6} MockUSDC</p><p>Welfare records a claim event/state benefit. It does not transfer a token.</p>{d.identityState.principal==='100000000'&&<>{button('Approve exactly 100 MockUSDC repayment',async()=>send(await call('repaymentTransaction',{approve:true})))}{button('Repay 100 MockUSDC',async()=>send(await call('repaymentTransaction')))}</>}</>}
 {d.summary&&<p>Private authenticated summary: ₹{(d.summary.incomeLast6MonthsPaise/100).toLocaleString()} over 6 completed months · {d.summary.activeMonthsLast12}/12 active completed months · history starts {new Date(d.summary.verifiedHistoryStartDay*86400000).toLocaleDateString()}.</p>}
 {!!d.history.length&&<details><summary>My recent actions</summary><ul>{d.history.map((h:any,i:number)=><li key={i}>{date(h.at)} · {h.event}</li>)}</ul></details>}</>)}
 {d?.role==='verifier'&&section('Create an eligibility request',<>{field('Passport ID',pid,Q)}<label>Policy <select value={consumer} onChange={e=>C(e.target.value)}><option value="loan">Loan · 100 MockUSDC</option><option value="welfare">Welfare · lifetime event claim</option><option value="gate">Custom verification</option></select></label>{consumer==='loan'&&<p>6-month average ≥ ₹20,000 · 12 months history · 9/12 active months · evidence ≤30 days old.</p>}{consumer==='welfare'&&<p>6 months history · 4/6 active months · evidence ≤90 days old. No income threshold.</p>}
 {consumer==='gate'&&<><label><input type="checkbox" checked={income} onChange={e=>A(e.target.checked)}/> Income criterion</label>{field('6-month average threshold (paise)',threshold,T)}<label><input type="checkbox" checked={history} onChange={e=>H(e.target.checked)}/> History criterion</label>{field('Minimum completed months',months,K)}<label><input type="checkbox" checked={activity} onChange={e=>V(e.target.checked)}/> Activity criterion</label>{field('Minimum active months out of 12',active,X)}</>}{button('Sign and send request',policy)}<p>Requests are immutable and expire after 15 minutes. Results disclose only PASS/FAIL.</p></>)}
 {d?.role==='admin'&&section('Controlled recovery',<><p>Revoke the old passport, authorize reissue on-chain, then approve one replacement address. That wallet must complete its own challenge, mock OTP and matching synthetic identity. Debt and welfare claims retain the original identity.</p>{field('Old passport ID',pid,Q)}{button('Revoke passport',async()=>send(await call('adminTransaction',{passportId:pid})))}{button('Authorize reissue on-chain',async()=>send(await call('adminTransaction',{passportId:pid,authorize:true})))}{field('Replacement wallet',replacement,J)}{button('Approve replacement binding',async()=>{const v=await call('recoveryAuthorize',{passportId:pid,wallet:replacement});N('Recovery identity for replacement onboarding: '+v.identity);})}</>)}
 {!!d?.requests?.length&&section('Eligibility requests',<>{d.requests.map((r:any)=><article key={r.id} style={{borderTop:'1px solid var(--line)',padding:'20px 0'}}><h3>{r.consumer} · passport #{r.passportId} · {r.status}</h3><ApplicationQr path={'/?requestId='+r.id} label='Open signed request (worker sign-in required)'/><p style={{overflowWrap:'anywhere'}}>Request {r.id} · expires {date(r.expiresAt)}</p><p>Income {r.policy.incomeEnabled==='1'?`≥ ₹${Number(r.policy.minAverageIncomePaise)/100} over ${r.policy.incomeWindowMonths} months`:'disabled'} · history {r.policy.historyEnabled==='1'?`≥ ${r.policy.minHistoryMonths} months`:'disabled'} · activity {r.policy.activityEnabled==='1'?`${r.policy.minActivePeriods}/${r.policy.activityWindow} periods`:'disabled'} · freshness {r.policy.maxEvidenceAgeDays} days</p>
 {r.result&&<p>Solidity verification: {['income','history','activity'].map(k=>`${k}: ${r.result.enabled[k]?r.result[k]:'disabled'}`).join(' · ')}</p>}
 {d.role==='worker'&&<>{r.status==='PENDING_WORKER'&&<>{button('Review and approve this policy',async()=>{const a=await call('approval',{id:r.id});if(!confirm('Approve exactly the displayed policy and current passport evidence?'))return;await call('approve',{id:r.id,signature:await sign(a)});await refresh();})}{button('Reject request',async()=>{await call('reject',{id:r.id});await refresh();})}</>}{r.status==='APPROVED'&&button('Authorize reconstruction and generate real proof',()=>action('RECONSTRUCT_EVIDENCE',r.id))}{r.status==='VERIFIED'&&r.consumer!=='gate'&&button(r.consumer==='welfare'?'Execute welfare claim':'Borrow 100 MockUSDC',async()=>send(await call('consumerTransaction',{id:r.id}),r.id))}</>}</article>)}</>)}
 </main>;
}
