'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {BrowserProvider,JsonRpcProvider,TypedDataEncoder,hexlify,toUtf8Bytes} from 'ethers';
import PortalShell from './PortalShell';
import PublicShell from './PublicShell';
import ApplicationQr from './ApplicationQr';
import Checklist from './Checklist';
import {workerPages,verifierPages} from '@/lib/portal';
type Role='public'|'worker'|'verifier'|'admin';
const personas=['RAMESH','SURESH','IMRAN','MANJUNATH','VENKATESH','FARHAN','ARJUN'];
const date=(v:any)=>v?new Date(Number(v)*1000).toLocaleString():'Not available';
const money=(v:any)=>'₹'+(Number(v??0)/100).toLocaleString('en-IN',{maximumFractionDigits:0});
const compact=(v:any)=>v?String(v).slice(0,8)+'…'+String(v).slice(-5):'—';
async function api(action:string,p:any={}){const r=await fetch('/api/app/'+action,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p),cache:'no-store'});const v=await r.json();if(!r.ok)throw Error(v.error??'Unable to complete this request');return v;}
const friendly=(s:string)=>({AUTHENTICATION_REQUIRED:'Your session has expired. Sign in again to continue.',WORKER_AUTHENTICATION_INCOMPLETE:'Complete phone verification before accessing your worker account.',ONBOARDING_REQUIRED:'Complete identity registration first.',OTP_NOT_ACTIVE:'No active code is available. Send a new phone code.',REGISTERED_PHONE_REQUIRED:'Use the phone number registered to this identity.',IDENTITY_ALREADY_BOUND:'This identity already has an account. Sign in or use controlled recovery.',CONDITION_FAILED:'The verified conditions do not meet this service’s policy.',REQUEST_EXPIRED:'This request expired or is no longer available. Ask for a new signed request.',NO_ACTIVE_LOAN:'There is no active loan to repay.',CONSENT_REQUIRED:'Review and sign financial-provider consent before continuing.',PHONE_LOGIN_NOT_REQUIRED:'Phone verification is already complete for this session.'} as Record<string,string>)[s]??s;
function Badge({value}:{value:string}){const good=['ACTIVE','PASS','VERIFIED','CLAIMED','BORROWED','COMPLETE'].includes(value),bad=['FAIL','REJECTED','REVOKED','EXPIRED'].includes(value);return <span className={'gv-badge '+(good?'good':bad?'bad':'wait')}>{value.replaceAll('_',' ')}</span>;}
function Card({title,children}:{title?:string;children:React.ReactNode}){return <section className="gv-card">{title&&<h2>{title}</h2>}{children}</section>;}
function Empty({title,children}:{title:string;children:React.ReactNode}){return <div className="gv-empty"><h2>{title}</h2>{children}</div>;}
function Criteria({p,result}:{p:any;result?:any}){return <div className="gv-criteria">{[['income','Income',p.incomeEnabled,`${money(p.minAverageIncomePaise)} monthly average`,`Last ${p.incomeWindowMonths} completed months`],['history','Work history',p.historyEnabled,`${p.minHistoryMonths} months minimum`,'Verified history'],['activity','Activity',p.activityEnabled,`${p.minActivePeriods} of ${p.activityWindow} active ${p.activityIsWeekly==='1'?'weeks':'months'}`,'Completed periods']].map(([key,label,enabled,target,caption])=><div key={key} className={result&&enabled==='1'?'condition-'+String(result[key]).toLowerCase():''}><span>{label}</span><strong>{enabled==='1'?target:'Not requested'}</strong><small>{enabled==='1'?caption:'No private value disclosed'}</small>{result&&enabled==='1'&&<p><Badge value={result[key]}/></p>}</div>)}</div>;}
export default function ProductApplication({role,view}:{role:Role;view:string}){
 const router=useRouter(),dev=view==='development';
 const [bundle,setBundle]=useState<any>(null),[d,setD]=useState<any>(null),[busy,setBusy]=useState('Loading your workspace'),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [authNext,setAuthNext]=useState('');
 const [mode,setMode]=useState(dev?'local':'external'),[wallet,setWallet]=useState(''),[intent,setIntent]=useState(view==='verifier-access'?'verifier':'worker');
 const [persona,setPersona]=useState(''),[phone,setPhone]=useState(dev?'+919000000001':''),[otp,setOtp]=useState(''),[mailbox,setMailbox]=useState<any>(null),[resendAt,setResendAt]=useState(0),[clock,setClock]=useState(Date.now()/1000);
 const [pid,setPid]=useState(''),[publicRecord,setPublicRecord]=useState<any>(null),[consumer,setConsumer]=useState('gate'),[evidence,setEvidence]=useState<any>(null),[authorization,setAuthorization]=useState<any>(null),[receipt,setReceipt]=useState<any>(null),[recovery,setRecovery]=useState(''),[replacement,setReplacement]=useState('');
 const [income,setIncome]=useState(false),[threshold,setThreshold]=useState('2000000'),[incomeWindow,setIncomeWindow]=useState('6'),[history,setHistory]=useState(false),[historyMonths,setHistoryMonths]=useState('12'),[activity,setActivity]=useState(false),[active,setActive]=useState('9'),[activityWindow,setActivityWindow]=useState('12'),[weekly,setWeekly]=useState(false),[freshness,setFreshness]=useState('30'),[expiry,setExpiry]=useState('15'),[selectedRequest,setSelectedRequest]=useState('');
 const sid=d?.onboarding?.sessionId,returning=d?.authentication==='PHONE_REQUIRED',phoneVerified=d?.onboarding?.state==='PHONE_VERIFIED',cooldown=Math.max(0,Math.ceil(resendAt-clock));
 const consentActive=d?.consent?.status==='ACTIVE',signedIn=d?.authentication==='COMPLETE',workerReady=signedIn&&d?.role==='worker'&&d?.passport;
 useEffect(()=>{const t=setInterval(()=>setClock(Date.now()/1000),1000);return()=>clearInterval(t);},[]);
 useEffect(()=>{let active=true;setEvidence(null);setAuthorization(null);api('info').then(async b=>{if(!active)return;setBundle(b);const q=new URLSearchParams(location.search),portal=q.get('portal');const next=q.get('next');setAuthNext(next?.startsWith('/worker/')&&!next.startsWith('//')?next:'');if(dev&&['worker','verifier','admin'].includes(portal??''))setIntent(portal!);setWallet(dev&&portal==='verifier'?b.roles.verifier:dev&&portal==='admin'?b.roles.admin:b.devWallets.find((a:any)=>a.label==='Worker 2').address);const id=q.get('passportId');if(id){setPid(id);if(view==='lookup')setPublicRecord(await api('publicPassport',{passportId:id}));}setSelectedRequest(q.get('requestId')??'');try{const current=await api('dashboard');if(active){setD(current);setWallet(current.wallet);setMode(b.devWallets.some((a:any)=>a.address.toLowerCase()===current.wallet.toLowerCase())?'local':'external');if(current.onboarding?.otp)setResendAt(current.onboarding.otp.resendAt);}}catch(e:any){if(role!=='public')router.replace('/signup?expired=1');}if(q.has('expired'))setError('Your session expired. Verify your wallet and phone again.');}).catch(e=>setError(friendly(e.message))).finally(()=>{if(active)setBusy('');});return()=>{active=false;};},[role,view,dev,router]);
 useEffect(()=>{if(d?.sessionExpiresAt&&clock>=d.sessionExpiresAt){setD(null);setEvidence(null);setMailbox(null);setAuthorization(null);setError('Your session expired. Sign in again.');if(role!=='public')router.replace('/signup?expired=1');}},[clock,d?.sessionExpiresAt,role,router]);
 async function refresh(){const current=await api('dashboard');setD(current);return current;}
 async function run(label:string,fn:()=>Promise<any>){setBusy(label);setError('');setNotice('');try{await fn();}catch(e:any){setError(friendly(e.message));if(e.message==='AUTHENTICATION_REQUIRED'){setD(null);setEvidence(null);setMailbox(null);setAuthorization(null);if(role!=='public')router.replace('/signup?expired=1');}}finally{setBusy('');}}
 const button=(label:string,fn:()=>Promise<any>,disabled=false,kind='')=><button className={'gv-button '+kind} disabled={!!busy||disabled} onClick={()=>void run(label,fn)}>{label}</button>;
 const field=(label:string,value:string,set:(v:string)=>void,type='text')=><label>{label}<input type={type} value={value} onChange={e=>set(e.target.value)}/></label>;
 const disconnect=async()=>{await api('logout');setD(null);setMailbox(null);setEvidence(null);setOtp('');setResendAt(0);router.push(dev?'/development':role==='verifier'?'/verifier-access':'/signup');};
 function destination(current:any){const next=new URLSearchParams(location.search).get('next');return current.role==='worker'&&next?.startsWith('/worker/')&&!next.startsWith('//')?next:current.role==='worker'?'/worker':current.role==='verifier'?'/verifier':'/admin';}
 async function provider(){if(mode==='local')return new JsonRpcProvider(bundle.rpcUrl,1337,{cacheTimeout:-1});if(!(window as any).ethereum)throw Error('No browser wallet detected. Open the development experience to use a local test wallet.');return new BrowserProvider((window as any).ethereum);}
 async function sign(a:any,message?:string){const p=await provider(),address=d?.wallet??wallet;try{if(mode==='local')return message?await p.send('eth_sign',[address,hexlify(toUtf8Bytes(message))]):await p.send('eth_signTypedData_v4',[address,TypedDataEncoder.getPayload(a.domain,a.types,a.value)]);const signer=await (p as BrowserProvider).getSigner(address);return message?await signer.signMessage(message):await signer.signTypedData(a.domain,a.types,a.value);}finally{if(mode==='local')p.destroy();}}
 async function connect(){let address=wallet;if(mode==='external'){const eth=(window as any).ethereum;if(!eth)throw Error('No browser wallet detected. Use the labeled development entry for the local experience.');address=(await eth.request({method:'eth_requestAccounts'}))[0];setWallet(address);try{await eth.request({method:'wallet_switchEthereumChain',params:[{chainId:'0x539'}]});}catch{await eth.request({method:'wallet_addEthereumChain',params:[{chainId:'0x539',chainName:'GigVault local',nativeCurrency:{name:'Local ETH',symbol:'ETH',decimals:18},rpcUrls:[bundle.rpcUrl]}]});}}
  const a=await api('challenge',{wallet:address}),p=await provider();try{const signature=mode==='local'?await p.send('eth_signTypedData_v4',[address,TypedDataEncoder.getPayload(a.domain,a.types,a.value)]):await (await (p as BrowserProvider).getSigner(address)).signTypedData(a.domain,a.types,a.value);await api('login',{nonce:a.value.nonce,signature});const current=await refresh();if(current.role!=='pending'&&(current.role!=='worker'||current.passport))router.push(destination(current));}finally{if(mode==='local')p.destroy();}}
 async function start(){const a=await api('onboardStart',{recoveryIdentity:recovery||undefined});await api('onboardWallet',{sessionId:a.sessionId,signature:await sign(null,a.message)});setMailbox(null);setOtp('');await refresh();}
 async function prepareAction(action:string,requestId?:string){const a=await api('actionChallenge',{action,requestId});setAuthorization(a);}
 async function authorize(){const a=authorization,v=await api('actionSubmit',{id:a.id,signature:await sign(null,a.message)});setAuthorization(null);if(a.value.action==='FETCH_FINANCIAL_DATA')setEvidence(v);const current=await refresh();setNotice(a.value.action==='RECONSTRUCT_EVIDENCE'?'Proof verified. Review the per-condition results below.':a.value.action==='CREATE_CONSENT'?'Signed consent is active.':a.value.action==='FETCH_FINANCIAL_DATA'?'Source signature and account owner verified.':'Blockchain transaction confirmed.');if(current.passport&&['MINT_PASSPORT','REISSUE_PASSPORT'].includes(a.value.action))router.push(destination(current));}
 async function send(tx:any,id?:string){const p=await provider();try{const signer=await (p as any).getSigner(d.wallet),sent=await signer.sendTransaction(tx);setNotice('Transaction submitted. Waiting for a block confirmation.');const r=await sent.wait();await api('transactionMined',{hash:r.hash,id});setReceipt({hash:r.hash,blockNumber:r.blockNumber,status:r.status});await refresh();setNotice('Transaction confirmed. Your on-chain state is updated.');}finally{if(mode==='local')p.destroy();}}
 async function newPolicy(){const criteria={incomeEnabled:income?'1':'0',incomeWindowMonths:income?incomeWindow:'0',minAverageIncomePaise:income?threshold:'0',historyEnabled:history?'1':'0',minHistoryMonths:history?historyMonths:'0',activityEnabled:activity?'1':'0',activityIsWeekly:activity&&weekly?'1':'0',activityWindow:activity?activityWindow:'0',minActivePeriods:activity?active:'0',maxEvidenceAgeDays:freshness};const a=await api('policyPrepare',{passportId:pid,consumer,criteria,expiresInSeconds:Number(expiry)*60});await api('policySubmit',{id:a.id,signature:await sign(a)});router.push('/verifier/results?requestId='+a.id);}
 const flash=<>{busy&&<div className="gv-alert" role="status">{busy}{busy.includes('proof')&&' — private proof generation may take a few minutes.'}</div>}{error&&<div className="gv-alert error" role="alert">{error}</div>}{notice&&<div className="gv-alert success" role="status">{notice}</div>}</>;
 const technical=<details><summary>Technical environment & account details</summary><p>Local EVM · real Groth16 · signed synthetic Mock FIP · MockUSDC test asset. Identity fallback and OTP delivery are simulations. No real Aadhaar or SMS verification.</p><p>Session expires {date(d?.sessionExpiresAt)}. State resets on server restart. Development RPC accounts are unlocked on loopback.</p><code>{d?.wallet}</code>{d?.passport&&<><p>Evidence v{d.passport.evidenceVersion} · schema {d.passport.schemaVersion} · source directory {d.passport.sourceDirectoryVersion}</p><code>{d.passport.evidenceCommitment}</code></>}</details>;
 const authorizePanel=authorization&&<Card title="Review your authorization"><p>{({CREATE_CONSENT:'Allow your financial provider to share evidence with GigVault.',MINT_PASSPORT:'Create your passport from signed, authenticated evidence.',REISSUE_PASSPORT:'Create an authorized replacement for your revoked passport.',REFRESH_PASSPORT:'Update your passport using newly authenticated financial evidence.',FETCH_FINANCIAL_DATA:'View your authenticated financial records privately.',RECONSTRUCT_EVIDENCE:'Reconstruct evidence and generate a proof for the approved policy.'} as Record<string,string>)[authorization.value.action]}</p><div className="gv-consent-scope"><p><strong>Provider:</strong> Apna Bank / synthetic Mock FIP</p><p><strong>Scope:</strong> authenticated transactions and account-owner profile through {date(authorization.scope.cutoff)}</p><p><strong>Use:</strong> passport evidence or this exact approved proof. Verifiers receive only requested PASS/FAIL and public context.</p><p>No persistent bank statement or private witness is stored in GigVault. You can revoke provider consent.</p></div><details><summary>Exact signed authorization</summary><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere',fontSize:11}}>{authorization.message}</pre></details><div className="gv-actions">{button(authorization.value.action==='RECONSTRUCT_EVIDENCE'?'Sign authorization & generate proof':'Sign authorization',authorize)}{button('Cancel',async()=>setAuthorization(null),false,'secondary')}</div></Card>;
 const receiptPanel=receipt&&<section className="gv-receipt" role="status"><strong>✓ Transaction confirmed</strong><p>Block {receipt.blockNumber} · local network · successful</p><details><summary>Transaction receipt</summary><code>{receipt.hash}</code></details></section>;
 const currentRequests=(d?.requests??[]).filter((r:any)=>view==='welfare'?r.consumer==='welfare':view==='credit'?r.consumer==='loan':true);
 const requests=<>{selectedRequest&&!currentRequests.some((r:any)=>r.id===selectedRequest)&&<div className="gv-alert error">This request expired, is unavailable, or belongs to another worker. No proof can be generated from this link.</div>}{currentRequests.length?currentRequests.map((r:any)=><article className="gv-request" key={r.id}><div className="gv-section-title"><h2>{r.consumer==='welfare'?'Gig Worker Support Benefit':r.consumer==='loan'?'Microcredit eligibility':'Private work verification'}</h2><Badge value={r.status}/></div><p className="gv-muted">Passport #{r.passportId} · expires {date(r.expiresAt)}</p><Criteria p={r.policy} result={r.result}/><p className="gv-muted">Freshness: at most {r.policy.maxEvidenceAgeDays==='0'?'no limit':r.policy.maxEvidenceAgeDays+' days'}. Verifier {compact(r.policy.verifierId)}. Your bank statement, exact income and activity counts stay private.</p>{r.result&&<><div className="gv-result-pipeline"><Checklist items={[{label:'Signed request',ok:true},{label:'Worker approval',ok:true},{label:'Current passport context',ok:r.contextStatus==='CURRENT',why:r.contextStatus?.replaceAll('_',' ')},{label:'Private proof verified',ok:true}]}/></div><p>{['income','history','activity'].some(k=>r.result.enabled[k]&&r.result[k]==='FAIL')?'The proof is valid. One or more requested conditions do not pass.':'All requested conditions pass.'}</p></>}
 {role==='worker'&&<div className="gv-actions">{r.status==='PENDING_WORKER'&&<>{button('Approve exact request',async()=>{const a=await api('approval',{id:r.id});await api('approve',{id:r.id,signature:await sign(a)});await refresh();})}{button('Decline',async()=>{await api('reject',{id:r.id});await refresh();},false,'secondary')}</>}{r.status==='APPROVED'&&button('Generate private proof',()=>prepareAction('RECONSTRUCT_EVIDENCE',r.id))}{r.status==='VERIFIED'&&r.consumer!=='gate'&&(view==='welfare'||view==='credit')&&button(r.consumer==='welfare'?'Claim support benefit':'Borrow 100 MockUSDC',async()=>send(await api('consumerTransaction',{id:r.id}),r.id),r.contextStatus!=='CURRENT'||['income','history','activity'].some(k=>r.result?.enabled[k]&&r.result[k]==='FAIL'))}{r.status==='VERIFIED'&&r.consumer!=='gate'&&view==='requests'&&<Link className="gv-button" href={r.consumer==='welfare'?'/worker/welfare':'/worker/credit'}>Continue to {r.consumer==='welfare'?'Welfare Benefits':'Microcredit'} →</Link>}</div>}
 {role==='verifier'&&<ApplicationQr path={'/worker/requests?requestId='+r.id} label="Share signed request with worker"/>}{r.receipt&&<div className="gv-receipt"><strong>Consumer action confirmed</strong><p>Block {r.receipt.blockNumber}</p><details><summary>Transaction receipt</summary><code>{r.receipt.hash}</code></details></div>}<details><summary>Signed request details</summary>{r.result&&<p>Actual Groth16 proof verified in Solidity. Consumer execution separately checks current passport context.</p>}<p>Request ID</p><code>{r.id}</code><p>Verifier</p><code>{r.policy.verifierId}</code></details></article>):<Card><Empty title="No requests yet"><p>{role==='worker'?'A verifier must send a signed request before you can approve a proof.':'Create a signed request for a passport holder.'}</p><Link className="gv-button secondary" href={role==='verifier'?'/verifier/new':'/worker/passport'}>{role==='verifier'?'Create a request':'Share your passport'}</Link></Empty></Card>}<p className="gv-muted">Requests expire at their signed deadline. Changing criteria requires a new request and new worker approval.</p></>;
 const lookup=<Card title="Find a public GigPassport"><p className="gv-muted">See public status and evidence freshness. Financial details are never available through this lookup.</p><div className="gv-form">{field('Passport ID',pid,setPid,'number')}{button('Look up passport',async()=>setPublicRecord(await api('publicPassport',{passportId:pid})),!pid)}</div>{publicRecord&&<div style={{marginTop:24}}><div className="gv-section-title"><h2>GigPassport #{publicRecord.passportId}</h2><Badge value={publicRecord.status}/></div><p>Evidence updated {date(publicRecord.evidenceUpdatedAt)} · version {publicRecord.evidenceVersion}</p>{role==='verifier'&&<Link className="gv-button" href={'/verifier/new?passportId='+publicRecord.passportId}>Start a signed request →</Link>}<details><summary>Public blockchain record</summary><p>Holder</p><code>{publicRecord.holderWallet}</code><p>Commitment</p><code>{publicRecord.evidenceCommitment}</code></details></div>}</Card>;
 function authContent(){const stage=!d?0:d.role==='pending'?(returning?1:!sid?0:!phoneVerified?1:2):!d.consent||!consentActive?3:!d.passport?4:5;
  return <PublicShell><main className="gv-auth-container"><aside className="gv-auth-story"><p className="gv-eyebrow">{intent==='verifier'?'VERIFY FACTS, PROTECT PRIVACY':'YOUR WORK PASSPORT STARTS HERE'}</p><h1>{intent==='verifier'?'Request only what you need to know.':'Make your work history portable.'}</h1><p className="gv-muted">{intent==='verifier'?'Sign an immutable request. The worker chooses whether to approve. You receive requested PASS/FAIL, never a bank statement.':'You control your evidence, your passport and every proof you share.'}</p>{intent==='worker'&&<ol className="gv-steps">{['Wallet ownership','Phone verification','Identity verification','Financial consent','Create passport'].map((label,i)=><li key={label} className={stage>i?'done':stage===i?'current':''}><span>{stage>i?'✓':i+1}</span>{label}</li>)}</ol>}<p className="gv-notice">Demo · synthetic identity and phone delivery. No real Aadhaar or SMS. Your passport and proof checks execute for real.</p></aside><section className="gv-auth-card">{dev&&<div className="gv-development"><strong>Development entry</strong><br/>Synthetic personas and unlocked local wallets are isolated here. They do not grant account access by themselves.</div>}<h2>{d?.role==='pending'?(returning?'Verify your registered phone':phoneVerified?'Complete identity verification':sid?'Verify your phone':'Verify account identity'):signedIn&&d.role==='worker'&&!d.passport?(consentActive?'Create your GigPassport':'Connect financial evidence'):d?'Your account is ready':intent==='verifier'?'Verifier access':'Welcome to GigVault'}</h2><p className="gv-muted">{!d?'Connect a wallet and sign a single-use server challenge.':d.role==='pending'?'Your worker sign-in is incomplete. Complete the required checks.':'Your account checks are complete.'}</p>{flash}
 {!d&&<div className="gv-form">{dev&&<><label>Workspace<select value={intent} onChange={e=>{const v=e.target.value;setIntent(v);setWallet(v==='verifier'?bundle?.roles.verifier:v==='admin'?bundle?.roles.admin:bundle?.devWallets.find((a:any)=>a.label==='Worker 2').address);}}><option value="worker">Worker</option><option value="verifier">Verifier</option><option value="admin">Recovery administrator</option></select></label><label>Wallet connection<select value={mode} onChange={e=>setMode(e.target.value)}><option value="local">Local development wallet</option><option value="external">Browser wallet</option></select></label>{mode==='local'&&<label>Development account<select value={wallet} onChange={e=>setWallet(e.target.value)}>{bundle?.devWallets.filter((a:any)=>intent==='verifier'?a.address===bundle.roles.verifier:intent==='admin'?a.address===bundle.roles.admin:!Object.values(bundle.roles).includes(a.address)).map((a:any)=><option key={a.address} value={a.address}>{a.label.replace('Worker','Development wallet')} · {compact(a.address)}</option>)}</select></label>}</>}{button('Connect wallet & sign challenge',connect,!bundle)}{!dev&&<p className="gv-muted">Need a local test wallet? <Link href={'/development?portal='+intent+(authNext?'&next='+encodeURIComponent(authNext):'')}>Enter the labeled development experience →</Link></p>}</div>}
 {d?.role==='pending'&&<>{!returning&&!sid&&<div className="gv-form">{field('Recovery identity (optional)',recovery,setRecovery)}{button('Sign registration challenge',start)}</div>}{(sid||returning)&&!phoneVerified&&<div className="gv-form"><p className="gv-muted">{returning?'Use your registered phone '+d.phoneMasked:'Verify your phone before identity binding.'}</p>{field('Indian phone number',phone,setPhone,'tel')}{button(cooldown?'Resend in '+cooldown+'s':'Send verification code',async()=>{const v=await api(returning?'loginOtpStart':'otpStart',{sessionId:sid,phone});setResendAt(Date.now()/1000+v.cooldownSeconds);setOtp('');setMailbox(await api(returning?'loginOtpMailbox':'otpMailbox',{sessionId:sid}));await refresh();},cooldown>0)}{button('Open demo OTP mailbox',async()=>setMailbox(await api(returning?'loginOtpMailbox':'otpMailbox',{sessionId:sid})),false,'secondary')}{mailbox&&<div className="gv-otp-box" role="status"><span>DEMO VERIFICATION CODE · NO SMS SENT</span>{mailbox.expiresAt>clock?<><strong>{mailbox.code}</strong><small>Expires in {Math.ceil(mailbox.expiresAt-clock)} seconds.</small></>:<p>This code expired. Send another.</p>}</div>}{field('Verification code',otp,setOtp)}{button('Verify phone',async()=>{await api(returning?'loginOtpVerify':'otpVerify',{sessionId:sid,code:otp});setMailbox(null);setOtp('');const current=await refresh();if(current.passport)router.push(destination(current));},!/^\d{6}$/.test(otp))}</div>}{phoneVerified&&<><p className="gv-notice">Genuine Anon Aadhaar is unavailable: no authentic proof artifacts are configured. Synthetic identity assertions are test-only.</p>{dev?<div className="gv-form"><label>Choose a synthetic test identity<select value={persona} onChange={e=>setPersona(e.target.value)}><option value="">Select a test persona</option>{personas.map(p=><option key={p}>{p}</option>)}</select></label>{button('Verify synthetic identity',async()=>{await api('identityCommit',{sessionId:sid,persona});await refresh();},!persona)}</div>:<Link className="gv-button secondary" href={'/development?portal=worker'+(authNext?'&next='+encodeURIComponent(authNext):'')}>Continue in test-only identity mode →</Link>}</>}</>}
 {signedIn&&d.role==='worker'&&!d.passport&&<><div className="gv-consent-scope"><strong>Apna Bank / synthetic financial provider</strong><p>Share authenticated transactions and account-owner profile for work evidence. GigVault verifies provenance and recognized payouts. Verifiers see only approved PASS/FAIL, never these records.</p><p>Consent lasts 30 minutes. Access can be revoked. No raw bank statement or private witness is retained in GigVault.</p></div>{!consentActive?button('Review and sign FIP consent',()=>prepareAction('CREATE_CONSENT')):button(d.reissueAllowed?'Create replacement GigPassport':'Create my GigPassport',()=>prepareAction(d.reissueAllowed?'REISSUE_PASSPORT':'MINT_PASSPORT'))}</>}
 {signedIn&&(d.role!=='worker'||d.passport)&&<Link className="gv-button" href={destination(d)}>Open {d.role==='worker'?'my dashboard':d.role+' workspace'} →</Link>}{d&&<div className="gv-actions">{button('Use another account',disconnect,false,'secondary')}</div>}{authorizePanel}{technical}</section></main></PublicShell>;
 }
 if(role==='public'&&view!=='lookup')return authContent();
 if(role==='public')return <PublicShell><main className="gv-content" style={{maxWidth:780}}><div className="gv-heading"><div><p className="gv-eyebrow">PUBLIC CREDENTIALS</p><h1>Find a passport</h1></div></div>{flash}{lookup}</main></PublicShell>;
 if(!d)return <PortalShell role={role} view={view}><div className="gv-loading">Validating your backend session…</div>{flash}</PortalShell>;
 const title=role==='worker'?workerPages[view]:role==='verifier'?verifierPages[view]:'Recovery Administration';
 let content:React.ReactNode=null;
 if(role==='worker'){
  if(view==='overview')content=<><div className="gv-welcome-banner"><div><h2>Welcome back, {d.worker?.name?.split(' ')[0]}.</h2><p>Your verified work history is ready to travel with you.</p></div><Badge value={d.passport.status}/></div><div className="gv-stats"><div className="gv-stat"><span>YOUR GIGPASSPORT</span><strong>#{d.passport.passportId}</strong><span>Evidence version {d.passport.evidenceVersion}</span></div><div className="gv-stat"><span>COMPLETED-MONTH ACTIVITY</span><strong>{d.summary?.activeMonthsLast12??'—'} / 12</strong><span>Private authenticated evidence</span></div><div className="gv-stat"><span>REQUESTS TO REVIEW</span><strong>{d.requests.filter((r:any)=>r.status==='PENDING_WORKER').length}</strong><span>You approve every disclosure</span></div></div><div className="gv-grid">{[['passport','▣','A passport that travels','View, share or refresh your credential.'],['requests','↗','Share proof, not statements','Review verification requests and exact criteria.'],['welfare','◇','Gig Worker Support Benefit','Verify eligibility, then claim lifetime support.'],['credit','⌁','Microcredit','Verify eligibility for 100 MockUSDC test credit.']].map(([v,icon,t,copy])=><Link className="gv-product-link" href={'/worker/'+v} key={v}><span>{icon}</span><h3>{t}</h3><p>{copy}</p></Link>)}</div></>;
  if(view==='passport')content=<><div className="gv-credential-grid"><div><div className="gv-passport"><p>GIGVAULT / VERIFIED WORK PASSPORT</p><h2>{d.worker.name}</h2><p>GIGPASSPORT #{d.passport.passportId}</p><div className="gv-passport-seal">G</div><span>Worker held · Non-transferable · Private proofs</span></div><Card title="Credential status"><Badge value={d.passport.status}/><p>Evidence updated {date(d.passport.evidenceUpdatedAt)}</p><p className="gv-muted">Freshness is evaluated against each signed request. Old evidence does not revoke your passport.</p><div className="gv-actions">{button('Review fresh provider consent',()=>prepareAction('CREATE_CONSENT'))}{button('Refresh passport evidence',()=>prepareAction('REFRESH_PASSPORT'),!consentActive||d.passport.status!=='ACTIVE','secondary')}</div>{technical}</Card></div><Card title="Share your public passport"><div className="gv-qr-panel"><ApplicationQr path={'/lookup?passportId='+d.passport.passportId} label="Open public GigPassport"/></div><p className="gv-muted">This link exposes the public credential only. A verifier must send a signed request to ask for a private proof.</p>{button('Copy public passport link',async()=>{await navigator.clipboard.writeText(new URL('/lookup?passportId='+d.passport.passportId,location.origin).href);setNotice('Public passport link copied.');},false,'secondary')}</Card></div><Card title="Passport transactions">{d.history.filter((h:any)=>h.hash&&h.event.includes('PASSPORT')).map((h:any,i:number)=><div className="gv-row" key={i}><div><strong>{h.event.replaceAll('_',' ')}</strong><p className="gv-muted">{date(h.at)}</p><details><summary>Confirmed transaction</summary><code>{h.hash}</code></details></div><Badge value="COMPLETE"/></div>)}</Card></>;
  if(view==='evidence')content=<><p className="gv-private-label">◉ Private to you · never shared with verifiers</p><div className="gv-stats"><div className="gv-stat"><span>RECOGNIZED INCOME / 6 MONTHS</span><strong>{money(d.summary?.incomeLast6MonthsPaise)}</strong><span>Completed months, including zero income</span></div><div className="gv-stat"><span>ACTIVE COMPLETED MONTHS</span><strong>{d.summary?.activeMonthsLast12??0} / 12</strong><span>Recognized payout in each active month</span></div><div className="gv-stat"><span>VERIFIED HISTORY START</span><strong style={{fontSize:19}}>{d.summary?new Date(d.summary.verifiedHistoryStartDay*86400000).toLocaleDateString():'—'}</strong><span>Derived from authenticated source data</span></div></div><Card title="Authenticated transactions"><p>Bank/FIP supplies provenance. GigVault separately classifies recognized payout sources. Personal transfers and narration-only claims do not count as gig income.</p>{button('Authorize private evidence view',()=>prepareAction('FETCH_FINANCIAL_DATA'),!consentActive)}{!consentActive&&<p className="gv-alert">Provider consent is inactive. <Link href="/worker/privacy">Renew consent →</Link></p>}{evidence&&<><p className="gv-private-label">✓ Source signature and account owner verified</p><p className="gv-muted">{evidence.total} authenticated rows · {evidence.counted} recognized payouts · showing latest {evidence.rows.length} · cutoff {date(evidence.cutoff)}</p><div className="gv-table-wrap"><table className="gv-table"><thead><tr><th colSpan={4}>BANK / FIP DATA</th><th colSpan={2}>GIGVAULT ANALYSIS</th></tr><tr><th>Date</th><th>Sender / description</th><th>Direction</th><th>Amount</th><th>Platform</th><th>Recognition</th></tr></thead><tbody>{evidence.rows.map((x:any,i:number)=><tr key={i}><td>{new Date(x.timestamp*1000).toLocaleDateString()}</td><td>{x.remitter}<br/><small>{x.description}</small></td><td>{x.direction}</td><td>{money(x.amountMinor)}</td><td>{x.platform??'—'}</td><td title={x.reason}>{x.category==='COUNTED'?'Recognized payout':'Excluded'}<br/><small>{x.reason}</small></td></tr>)}</tbody></table></div><p className="gv-muted">Loaded only into this page’s memory. Leaving this page discards the table.</p></>}</Card></>;
  if(view==='privacy')content=<><Card title="Your financial-provider consent"><div className="gv-section-title"><strong>Apna Bank / synthetic Mock FIP</strong><Badge value={d.consent?.status??'NOT_GRANTED'}/></div><div className="gv-consent-scope"><p><strong>Data:</strong> authenticated transactions and account-owner profile.</p><p><strong>Purpose:</strong> derive work evidence, create/refresh your passport and reconstruct explicitly approved proofs.</p><p><strong>Disclosure:</strong> only the requested PASS/FAIL and public passport context reach verifiers.</p><p><strong>Retention:</strong> source records remain with Mock FIP; GigVault does not persist raw records or private evidence snapshots.</p>{d.consent&&<><p><strong>Scope cutoff:</strong> {date(d.consent.scope.toTimestamp)}</p><p><strong>Expires:</strong> {date(d.consent.expiresAt)}</p></>}</div><div className="gv-actions">{button('Review and sign new consent',()=>prepareAction('CREATE_CONSENT'))}{button('Revoke provider access',async()=>{await api('revokeConsent');await refresh();setEvidence(null);setNotice('Provider access revoked. New evidence retrieval and reconstruction are blocked.');},!consentActive,'danger')}</div><p className="gv-muted">Revoking consent does not revoke your on-chain passport or undo a proof already verified.</p></Card><Card title="Every proof needs your approval"><p>Verifiers sign exact criteria. You approve or decline each request. Changing a criterion requires a new signed request and approval.</p><Link href="/worker/requests" className="gv-text-link">Review my requests →</Link></Card></>;
  if(view==='requests')content=requests;
  if(view==='welfare')content=<><Card title="Gig Worker Support Benefit"><div className="gv-section-title"><p>Independent support service · one lifetime claim per identity</p><Badge value={d.identityState.claimed?'CLAIMED':'NOT_CLAIMED'}/></div><p>Requires an ACTIVE passport, at least 6 months of history, 4 active months in the latest 6 completed months, and evidence no older than 90 days. No income threshold.</p><p className="gv-notice">Verify eligibility first. A separate claim transaction records the benefit. This local benefit is an event/state claim; it transfers no token.</p>{d.identityState.claimed&&<p className="gv-alert success">Your lifetime benefit is claimed. Passport replacement cannot reset this status.</p>}</Card>{requests}</>;
  if(view==='credit')content=<><div className="gv-grid"><Card title="Microcredit"><p className="gv-muted">Independent lending policy · local test asset</p><div className="gv-loan-amount">100 <span style={{fontSize:19}}>MockUSDC</span></div><p>Requires ₹20,000 average income over 6 completed months, 12 months of verified history, 9 active months of the last 12, evidence within 30 days and no active loan.</p><p className="gv-muted">No interest or collateral in this local service. Verify first, then separately borrow.</p></Card><Card title="Your loan balance"><div className="gv-loan-amount">{Number(d.identityState.principal)/1e6} <span style={{fontSize:19}}>MockUSDC</span></div><p>Wallet balance: {Number(d.balanceMockUSDC)/1e6} MockUSDC</p><Badge value={d.identityState.principal==='0'?'NO_ACTIVE_LOAN':'BORROWED'}/>{d.identityState.principal==='100000000'&&<div className="gv-actions">{button('Approve exact repayment',async()=>send(await api('repaymentTransaction',{approve:true})))}{button('Repay 100 MockUSDC',async()=>send(await api('repaymentTransaction')),Number(d.balanceMockUSDC)<100000000,'secondary')}</div>}<p className="gv-muted">Debt follows your stable identity through recovery. The replacement wallet needs actual test-token funds to repay.</p></Card></div>{requests}</>;
  if(view==='activity')content=<><Card title="Your recent activity">{d.history.length?d.history.map((h:any,i:number)=><div className="gv-row" key={i}><div><strong>{h.event.replaceAll('_',' ')}</strong><p className="gv-muted">{date(h.at)}</p>{h.hash&&<details><summary>Transaction receipt</summary><code>{h.hash}</code></details>}</div><Badge value="COMPLETE"/></div>):<Empty title="No recent activity"><p>Your completed actions will appear here.</p></Empty>}<p className="gv-muted">At most 20 actions or 90 days, whichever is smaller. No private bank records or witnesses in this history.</p></Card><Card title="Account & session"><p>{d.worker.name} · protected phone {d.worker.phoneMasked}</p><p>Session expires {date(d.sessionExpiresAt)}.</p><div className="gv-actions">{button('Refresh live state',refresh,false,'secondary')}{button('Sign out',disconnect,false,'secondary')}</div>{technical}<Link href="/development?portal=admin" className="gv-text-link">Controlled recovery administration →</Link></Card></>;
 }
 if(role==='verifier'){
  if(view==='overview')content=<><div className="gv-welcome-banner"><div><h2>Verify facts. Respect privacy.</h2><p>Request exactly the evidence your service needs.</p></div><Link className="gv-button" href="/verifier/new">New request →</Link></div><div className="gv-stats"><div className="gv-stat"><span>ACTIVE REQUESTS</span><strong>{d.requests.length}</strong></div><div className="gv-stat"><span>AWAITING WORKER APPROVAL</span><strong>{d.requests.filter((r:any)=>r.status==='PENDING_WORKER').length}</strong></div><div className="gv-stat"><span>VERIFIED PROOFS</span><strong>{d.requests.filter((r:any)=>!!r.result).length}</strong></div></div><div className="gv-grid"><Link className="gv-product-link" href="/verifier/lookup"><span>▣</span><h3>Find a GigPassport</h3><p>Read public chain state before creating a request.</p></Link><Link className="gv-product-link" href="/verifier/results"><span>◈</span><h3>Live proof results</h3><p>Current passport context, real verification and requested PASS/FAIL.</p></Link></div></>;
  if(view==='lookup')content=lookup;
  if(view==='new')content=<Card title="Create an immutable verification request"><p className="gv-muted">The worker sees your exact criteria, requesting wallet and deadline before approving. Changing any criterion means a new request.</p><div className="gv-form">{field('Passport ID',pid,setPid,'number')}<label>Request policy<select value={consumer} onChange={e=>setConsumer(e.target.value)}><option value="gate">Custom fact verification</option><option value="welfare">Gig Worker Support Benefit</option><option value="loan">Microcredit · 100 MockUSDC</option></select></label>{consumer==='gate'?<><label className="gv-checkbox"><input type="checkbox" checked={income} onChange={e=>setIncome(e.target.checked)}/> Minimum average income</label>{income&&<div className="gv-grid">{field('Average income threshold (paise)',threshold,setThreshold,'number')}{field('Completed-month window (1–36)',incomeWindow,setIncomeWindow,'number')}</div>}<label className="gv-checkbox"><input type="checkbox" checked={history} onChange={e=>setHistory(e.target.checked)}/> Minimum verified history</label>{history&&field('Minimum history in months',historyMonths,setHistoryMonths,'number')}<label className="gv-checkbox"><input type="checkbox" checked={activity} onChange={e=>setActivity(e.target.checked)}/> Minimum work activity</label>{activity&&<><label>Continuity unit<select value={weekly?'week':'month'} onChange={e=>setWeekly(e.target.value==='week')}><option value="month">Completed months</option><option value="week">Completed ISO weeks</option></select></label><div className="gv-grid">{field('Window length',activityWindow,setActivityWindow,'number')}{field('Minimum active periods',active,setActive,'number')}</div></>}{field('Maximum evidence age in days (0 = unrestricted)',freshness,setFreshness,'number')}</>:<p className="gv-notice">{consumer==='loan'?'Exactly ₹20,000 average over 6 months; 12 months history; 9/12 active months; evidence ≤30 days.':'Exactly 6 months history; 4/6 active months; evidence ≤90 days; no income criterion.'} These consumer rules cannot be relaxed.</p>}{field('Request expires in minutes (1–60)',expiry,setExpiry,'number')}{button('Sign and send verification request',newPolicy,!pid)}</div></Card>;
  if(view==='results'||view==='history')content=<>{requests}<div className="gv-actions">{button('Refresh live request status',refresh,false,'secondary')}</div></>;
 }
 if(role==='admin')content=<Card title="Controlled passport recovery"><p>Revoke the old passport, authorize reissue on-chain, then approve one replacement wallet. That worker must reverify phone and matching identity and sign fresh financial consent.</p><div className="gv-form">{field('Old passport ID',pid,setPid,'number')}<div className="gv-actions">{button('Revoke passport',async()=>send(await api('adminTransaction',{passportId:pid})),!pid,'danger')}{button('Authorize reissue',async()=>send(await api('adminTransaction',{passportId:pid,authorize:true})),!pid,'secondary')}</div>{field('Replacement wallet address',replacement,setReplacement)}{button('Approve replacement binding',async()=>{const v=await api('recoveryAuthorize',{passportId:pid,wallet:replacement});setNotice('Recovery identity: '+v.identity);},!replacement||!pid)}</div><p className="gv-notice">The old wallet loses service access. Lifetime benefit and outstanding debt remain tied to the original stable identity.</p>{technical}</Card>;
 return <PortalShell role={role} view={view}><div className="gv-heading"><div><p className="gv-eyebrow">{role==='worker'?'YOUR WORK, UNDER YOUR CONTROL':'PRIVATE FACT VERIFICATION'}</p><h1>{title}</h1><p>{role==='worker'?'Your evidence stays yours. Share only the proof a service needs.':'Signed requests and real verification. No private financial details.'}</p></div><div className="gv-actions" style={{margin:0}}>{button('Refresh',refresh,false,'secondary')}{button('Sign out',disconnect,false,'secondary')}</div></div>{flash}{receiptPanel}{authorizePanel}{content}</PortalShell>;
}
