'use client';
import PublicShell from './PublicShell';
import Link from 'next/link';

const copy:any={create:{title:'Create your account',story:'Your work deserves a passport.',description:'A few simple steps. One portable record of your work.',label:'GET STARTED'},signin:{title:'Welcome back',story:'Your passport. Ready when you are.',description:'Return to your verified account and pick up where you left off.',label:'YOUR ACCOUNT'},recover:{title:'Recover your account',story:'Keep your identity. Restore your access.',description:'A guided replacement keeps your work history, benefits and obligations together.',label:'ACCOUNT RECOVERY'}};
export default function WorkerEntry(p:any){
 const {journey,d,busy,phone,otp,mailbox,clock,cooldown,identity,mode,wallet,bundle,sid,phoneVerified,consentActive,recovery,passportId,dev}=p;
 const text=copy[journey],registered=d?.role==='worker',inRecovery=journey==='recover'||d?.onboarding?.recovery;
 const progress=registered?(d.passport?4:consentActive?3:2):phoneVerified?1:0;
 const phoneStep=(journey==='create'||inRecovery||mode==='managed'&&journey==='signin')&&d?.role==='pending'&&!!sid&&!phoneVerified;
 const identityStep=(journey==='create'||inRecovery||mode==='managed'&&journey==='signin')&&phoneVerified;
 return <PublicShell><main className="gv-auth-container gv-worker-entry">
  <aside className="gv-auth-story"><p className="gv-eyebrow">{text.label}</p><h1>{text.story}</h1><p>{text.description}</p>
   {journey==='create'||inRecovery?<><ol className="gv-steps" aria-label="Account progress">{['Verify phone','Verify identity','Financial consent','Create passport'].map((label,i)=><li key={label} className={progress>i?'done':progress===i?'current':''} aria-current={progress===i?'step':undefined}><span>{progress>i?'✓':i+1}</span>{label}</li>)}</ol><div className="gv-entry-progress" role="progressbar" aria-label="Account setup" aria-valuemin={0} aria-valuemax={4} aria-valuenow={progress}><span style={{width:(progress/4*100)+'%'}}/></div><p className="gv-muted">{progress} of 4 steps complete</p></>:<div className="gv-entry-promise"><h3>Continue your journey</h3><p>Your registered identity and passport are restored from your account.</p><h3>Your evidence stays private</h3><p>You choose which verification requests to approve.</p></div>}
  </aside>
  <section className="gv-auth-card"><nav className="gv-entry-tabs" aria-label="Account journeys">{[['create','Create Account'],['signin','Sign In'],['recover','Recover Account']].map(([key,label])=><button key={key} className={'gv-button '+(journey===key?'':'secondary')} aria-pressed={journey===key} disabled={!!busy} onClick={()=>p.chooseJourney(key)}>{label}</button>)}</nav>
   {p.flash}<div key={journey+'-'+progress+'-'+!!sid} className="gv-entry-stage">
   <p className="gv-eyebrow">{phoneStep?'PHONE VERIFICATION':identityStep?'IDENTITY VERIFICATION':registered&&!d.passport?'ACCOUNT VERIFIED':text.label}</p>
   <h2>{phoneStep?'Verify Phone':identityStep?'Aadhaar Verification':registered&&!d.passport?(consentActive?'Create your GigPassport':'Connect financial evidence'):text.title}</h2>
   {journey==='create'&&!sid&&!registered&&<div className="gv-form"><p>Start with your phone number. We’ll guide you through identity verification and creating your passport.</p><label>Indian phone number<input type="tel" inputMode="tel" autoComplete="tel" placeholder="+91 90000 00000" value={phone} onChange={e=>p.setPhone(e.target.value)}/></label>{p.button('Continue to phone verification',p.createAccount,!bundle||!/^\+91\d{10}$/.test(phone.replace(/\s/g,'')))}<p className="gv-muted">{mode==='managed'?'Your account connection is created automatically after verification.':'Use Connection options below to approve your existing wallet challenge.'}</p></div>}
   {journey==='signin'&&mode==='managed'&&!sid&&!registered&&<div className="gv-form"><p>Enter your registered phone number to securely access your GigPassport.</p><label>Indian phone number<input type="tel" inputMode="tel" autoComplete="tel" value={phone} onChange={e=>p.setPhone(e.target.value)}/></label>{p.button('Verify Phone',p.signIn,!bundle||!/^\+91\d{10}$/.test(phone.replace(/\s/g,'')))}</div>}
   {journey==='signin'&&mode!=='managed'&&(!registered)&&<div className="gv-form"><p>Continue using your existing account connection to securely restore your GigPassport.</p><div className="gv-entry-promise"><strong>Already registered?</strong><p>Continue directly to your passport. You won’t create another identity or repeat registration.</p></div>{!d?p.button('Sign in to my account',p.signIn,!bundle):<div className="gv-notice"><strong>No registered account found</strong><p>This connection has not completed registration.</p>{p.button('Create a new account',async()=>p.chooseJourney('create'))}{p.button('Use a different connection',p.disconnect,false,'secondary')}</div>}</div>}
   {journey==='recover'&&!registered&&(!sid)&&<div className="gv-form"><p>Reverify the original phone and identity after the administrator has authorized your replacement connection. First, find your original passport and check that approval.</p>{mode==='managed'&&<p className="gv-notice">Select the approved replacement connection in Connection options below. Automatic replacement-wallet recovery is not supported yet.</p>}<label>Original passport reference<input type="number" inputMode="numeric" min="1" value={passportId} placeholder="e.g. 1" onChange={e=>{p.setPassportId(e.target.value);p.clearRecovery();}}/></label>{p.button('Check my recovery access',p.checkRecovery,!bundle||mode==='managed'||!/^\d+$/.test(passportId)||Number(passportId)<1)}</div>}
   {journey==='recover'&&recovery&&<div className="gv-entry-recovery" role="status"><h3>Recovery status</h3><dl><div><dt>Original passport</dt><dd>{recovery.passportStatus}</dd></div><div><dt>Replacement issuance</dt><dd>{recovery.replacementPassportId?'Completed':recovery.reissueAllowed===null?'Unavailable to this connection':recovery.reissueAllowed?'Authorized':'Awaiting administrator'}</dd></div><div><dt>This replacement connection</dt><dd>{recovery.replacementApproved&&recovery.expiresAt>clock?'Approved':'Not approved'}</dd></div></dl>{recovery.replacementPassportId?<p>Replacement passport #{recovery.replacementPassportId} has been issued. Sign in using its registered connection.</p>:recovery.replacementApproved&&recovery.expiresAt>clock?<><p>Use the original verified phone ({recovery.phoneMasked}) and the same identity. Approval expires {new Date(recovery.expiresAt*1000).toLocaleTimeString()}.</p>{!sid&&d?.role==='pending'&&p.button('Begin verified recovery',p.startRecovery,!recovery.reissueAllowed)}</>:<p>Next: ask the authorized administrator to revoke the original passport, authorize replacement issuance and approve your replacement wallet. Checking status does not grant recovery access.</p>}</div>}
   {phoneStep&&<div className="gv-form"><p>{inRecovery?'Verify the original phone linked to your identity.':'Confirm your number before verifying your identity.'}</p><label>Indian phone number<input type="tel" inputMode="tel" autoComplete="tel" value={phone} readOnly={mode==='managed'} onChange={e=>p.setPhone(e.target.value)}/></label>{p.button(cooldown?'Resend in '+cooldown+'s':'Send verification code',p.sendOtp,cooldown>0||!/^\+91\d{10}$/.test(phone.replace(/\s/g,'')))}{mailbox&&<div className="gv-otp-box" role="status"><span>VERIFICATION CODE</span>{mailbox.expiresAt>clock?<><strong>{mailbox.code}</strong><small>Expires in {Math.ceil(mailbox.expiresAt-clock)} seconds</small></>:<p>Code expired. Send another.</p>}</div>}<label>Verification code<input inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={otp} placeholder="6-digit code" onChange={e=>p.setOtp(e.target.value.replace(/\D/g,''))}/></label>{p.button('Verify phone and continue',p.verifyOtp,!/^\d{6}$/.test(otp))}{p.button('View verification code',p.openMailbox,false,'secondary')}</div>}
   {identityStep&&<div className="gv-form"><p>Verify your identity to secure your GigPassport.</p><label>Aadhaar Number<input inputMode="numeric" autoComplete="off" maxLength={14} placeholder="0000 0000 0000" value={identity.replace(/(.{4})(?=.)/g,'$1 ')} onChange={e=>p.setIdentity(e.target.value.replace(/\D/g,'').slice(0,12))}/></label>{p.button('Verify Aadhaar',p.verifyIdentity,!/^\d{12}$/.test(identity))}</div>}
   {registered&&!d.passport&&<div className="gv-form"><p className="gv-notice">Identity verification complete · {d.worker.name}</p>{!consentActive?<><p>Choose to let your financial provider supply authenticated work evidence. Verifiers receive only the facts you approve.</p><p className="gv-muted">Review the scope before signing. Consent lasts 30 minutes and can be revoked.</p>{p.button('Review financial consent',()=>p.prepareAction('CREATE_CONSENT'))}</>:<><p>Your signed consent is active. Create your passport from your verified work evidence.</p>{p.button(d.reissueAllowed?'Create replacement GigPassport':'Create GigPassport',()=>p.prepareAction(d.reissueAllowed?'REISSUE_PASSPORT':'MINT_PASSPORT'))}</>}</div>}
   {registered&&d.passport&&<div className="gv-entry-promise"><h3>{d.worker.name}</h3><p>Your passport is <strong>{d.passport.status}</strong>.</p>{journey==='recover'&&<p>Check the original passport using an approved replacement connection. Signing in as its holder does not transfer access.</p>}<Link className="gv-button" href={p.destination(d)}>Open my dashboard →</Link>{p.button('Use a different connection',p.disconnect,false,'secondary')}</div>}
   </div>{p.authorizePanel}
   <details className="gv-entry-demo"><summary>Connection options</summary><p>Choose a local unlocked test wallet for the ideathon; no browser extension is required. Browser-wallet challenges remain supported. These are fictional evaluation accounts, not production signing keys.</p><div className="gv-form"><label>Connection method<select disabled={!!d||!!busy} value={mode} onChange={e=>p.setMode(e.target.value)}><option value="managed">Automatic account</option><option value="external">Browser wallet</option><option value="local">Local account</option></select></label>{mode==='local'&&<label>Evaluation connection<select disabled={!!d||!!busy} value={wallet} onChange={e=>p.setWallet(e.target.value)}>{bundle?.devWallets.filter((a:any)=>!Object.values(bundle.roles).includes(a.address)).map((a:any,i:number)=><option key={a.address} value={a.address}>Evaluation account {String.fromCharCode(65+i)} · {a.address.slice(0,8)}…</option>)}</select></label>}{d&&p.button('Disconnect to change connection',p.disconnect,false,'secondary')}</div><p>OTP delivery and Aadhaar identifiers are simulated. No SMS or UIDAI integration. Matching a fictional identifier alone is not authentication. Automatic accounts use backend-held, encrypted local keys. Simulated OTP does not prove phone possession; this isolated environment is not production authentication.</p>{dev&&<Link href="/verifier-access">Verifier access →</Link>}</details>
   {p.technical}
  </section>
 </main></PublicShell>;
}
