import {test} from 'node:test';
import assert from 'node:assert/strict';
import {EventEmitter} from 'node:events';
import {connectBrowserWallet,verifyBrowserWallet,subscribeWalletChanges} from '../../frontend/lib/browser-wallet.mjs';
const wallet='0x1234567890123456789012345678901234567890';
function provider(){const eth=new EventEmitter();eth.accounts=[wallet];eth.chain='0x539';eth.methods=[];eth.request=async({method})=>{eth.methods.push(method);if(method==='eth_chainId')return eth.chain;if(method==='eth_accounts'||method==='eth_requestAccounts')return eth.accounts;return null;};return eth;}
test('EIP-1193 connect requests accounts and checks the actual active local chain',async()=>{const eth=provider();assert.equal(await connectBrowserWallet(eth,'http://127.0.0.1:8545'),wallet);assert.deepEqual(eth.methods,['eth_requestAccounts','wallet_switchEthereumChain','eth_chainId','eth_accounts']);});
test('wallet rejection is propagated and never treated as an unknown network',async()=>{const eth=provider(),request=eth.request;eth.request=async p=>{if(p.method==='wallet_switchEthereumChain')throw Object.assign(Error('User rejected'),{code:4001});return request(p);};await assert.rejects(()=>connectBrowserWallet(eth,'http://localhost:8545'),/User rejected/);assert.ok(!eth.methods.includes('wallet_addEthereumChain'));});
test('only a missing chain adds and explicitly selects the configured loopback chain',async()=>{const eth=provider(),request=eth.request;let added=false,selected=false;eth.request=async p=>{if(p.method==='wallet_switchEthereumChain'){if(!added)throw Object.assign(Error('Missing'),{code:4902});selected=true;return null;}if(p.method==='wallet_addEthereumChain'){assert.equal(p.params[0].chainId,'0x539');assert.deepEqual(p.params[0].rpcUrls,['http://127.0.0.1:8545']);added=true;return null;}return request(p);};await connectBrowserWallet(eth,'http://127.0.0.1:8545');assert.ok(added&&selected);});
test('signature and transaction preflight reject changed accounts or networks',async()=>{const eth=provider();eth.chain='0x1';await assert.rejects(()=>verifyBrowserWallet(eth,wallet),/WALLET_CHAIN_CHANGED/);eth.chain='0x539';eth.accounts=[];await assert.rejects(()=>verifyBrowserWallet(eth,wallet),/WALLET_ACCOUNT_CHANGED/);});
test('account switching, disconnection and network events invalidate the session and detach cleanly',()=>{const eth=provider();let invalidations=0;const remove=subscribeWalletChanges(eth,wallet,()=>invalidations++);eth.emit('accountsChanged',[wallet]);assert.equal(invalidations,0);eth.emit('accountsChanged',[]);eth.emit('accountsChanged',['0xother']);eth.emit('chainChanged','0x1');eth.emit('disconnect');assert.equal(invalidations,4);remove();eth.emit('disconnect');assert.equal(invalidations,4);assert.equal(eth.listenerCount('accountsChanged'),0);});
