/**
 * GigVault - Real Anon Aadhaar Verifier (Mode A: Official Cryptographic Verification)
 * 
 * Verifies real Groth16 zero-knowledge proofs generated by Anon Aadhaar circuits
 * over UIDAI RSA signatures on Aadhaar QR codes.
 * 
 * Cryptographic & Architectural Invariants:
 * 1. Executes genuine snarkjs.groth16.verify on trusted server side.
 * 2. Strict public key hash verification against trusted UIDAI RSA roots.
 * 3. Enforces cryptographic binding between the proof's public signal and the
 *    worker's EVM wallet address / server challenge to prevent proof theft.
 * 4. NEVER stores raw Aadhaar numbers, QR payloads, or demographic records.
 * 5. Fails closed if verification key is missing or proof fails mathematical verification.
 * 6. NEVER falls back silently to mock verification.
 */

// @ts-ignore - snarkjs does not ship full standard TS declarations in all versions
import * as snarkjs from 'snarkjs';
import crypto from 'node:crypto';
import {
  type IAadhaarProofVerifier,
  type VerifyAadhaarRequest,
  type VerifyAadhaarResult,
  AadhaarTrustMode,
  AadhaarTrustModeMismatchError,
  AnonAadhaarProofMalformedError,
  AnonAadhaarProofTamperedError,
  AnonAadhaarSignalBindingMismatchError,
  AnonAadhaarPubkeyNotTrustedError,
  AnonAadhaarVerificationKeyMissingError,
} from './types.js';

export interface RealAnonAadhaarVerifierOptions {
  verificationKey?: any; // Groth16 snarkjs verification key JSON
  trustedPubkeyHashes?: string[]; // Allowed UIDAI public key hashes (string decimal or hex)
  allowTestKeys?: boolean; // Whether to accept Anon Aadhaar test/staging QR public key
}

/**
 * Known UIDAI / Anon Aadhaar Public Key Hashes (BN254 Field Elements as decimal strings)
 */
export const ANON_AADHAAR_TEST_PUBKEY_HASH =
  '153344406208579485121408801822606821217596075402008436573802272506162804618';

export class RealAnonAadhaarVerifier implements IAadhaarProofVerifier {
  private verificationKey?: any;
  private trustedPubkeyHashes: Set<string>;

  constructor(options: RealAnonAadhaarVerifierOptions = {}) {
    this.verificationKey = options.verificationKey;
    this.trustedPubkeyHashes = new Set(options.trustedPubkeyHashes || []);

    if (options.allowTestKeys ?? true) {
      this.trustedPubkeyHashes.add(ANON_AADHAAR_TEST_PUBKEY_HASH);
    }
  }

  public getTrustMode(): AadhaarTrustMode {
    return 'REAL_ANON_AADHAAR';
  }

  public setVerificationKey(vkey: any): void {
    this.verificationKey = vkey;
  }

  public addTrustedPubkeyHash(hash: string): void {
    this.trustedPubkeyHashes.add(hash.trim());
  }

  /**
   * Check whether a submitted signal satisfies the required binding
   * to the expected wallet address or server challenge.
   */
  public isSignalBound(
    submittedSignal: string,
    expectedWalletAddress: string,
    expectedChallenge: string
  ): boolean {
    const cleanSignal = submittedSignal.trim();

    // 1. Check wallet address as BigInt decimal string (standard Anon Aadhaar signal binding)
    try {
      const cleanWallet = expectedWalletAddress.toLowerCase().trim();
      const walletBigInt = BigInt(cleanWallet).toString();
      if (cleanSignal === walletBigInt) {
        return true;
      }
    } catch {
      // Ignore conversion error
    }

    // 2. Check challenge nonce direct match
    if (cleanSignal === expectedChallenge.trim()) {
      return true;
    }

    // 3. Check challenge nonce as BigInt
    try {
      const challengeBigInt = BigInt(
        expectedChallenge.startsWith('0x') ? expectedChallenge : '0x' + expectedChallenge
      ).toString();
      if (cleanSignal === challengeBigInt) {
        return true;
      }
    } catch {
      // Ignore conversion error
    }

    // 4. Check sha256 hash of challenge reduced to field
    try {
      const hashHex = crypto.createHash('sha256').update(expectedChallenge).digest('hex');
      const hashBigInt = BigInt('0x' + hashHex).toString();
      if (cleanSignal === hashBigInt) {
        return true;
      }
    } catch {
      // Ignore
    }

    return false;
  }

  public async verify(request: VerifyAadhaarRequest): Promise<VerifyAadhaarResult> {
    // 1. Strict mode separation
    if (request.mode !== 'REAL_ANON_AADHAAR') {
      throw new AadhaarTrustModeMismatchError('REAL_ANON_AADHAAR', request.mode);
    }

    const payload = request.realProofPayload;
    if (!payload) {
      throw new AnonAadhaarProofMalformedError('Missing realProofPayload in request');
    }

    if (!payload.groth16Proof || !payload.pubkeyHash || !payload.nullifier || !payload.signal) {
      throw new AnonAadhaarProofMalformedError(
        'realProofPayload must include groth16Proof, pubkeyHash, nullifier, and signal'
      );
    }

    // 2. Trust Root: Verify UIDAI public key hash against pinned trusted hashes
    const cleanPubkeyHash = payload.pubkeyHash.trim();
    if (!this.trustedPubkeyHashes.has(cleanPubkeyHash)) {
      throw new AnonAadhaarPubkeyNotTrustedError(cleanPubkeyHash);
    }

    // 3. Signal Binding: Proof MUST be bound to the onboarding session's wallet or challenge
    const signalBound = this.isSignalBound(
      payload.signal,
      request.expectedWalletAddress,
      request.expectedChallenge
    );

    if (!signalBound) {
      throw new AnonAadhaarSignalBindingMismatchError(
        `wallet:${request.expectedWalletAddress} | challenge:${request.expectedChallenge}`,
        payload.signal
      );
    }

    // 4. Cryptographic Proof Verification: Verify Groth16 proof using snarkjs
    if (!this.verificationKey) {
      throw new AnonAadhaarVerificationKeyMissingError(
        'Real Anon Aadhaar verification key is not configured on this server instance. Proof verification cannot proceed.'
      );
    }

    // Construct public signals array matching circuit expectations
    let publicSignals = payload.publicSignals;
    if (!publicSignals || publicSignals.length === 0) {
      publicSignals = [
        payload.pubkeyHash,
        payload.nullifier,
        String(payload.timestamp),
        payload.ageAbove18 ? '1' : '0',
        payload.gender || '0',
        payload.pincode || '0',
        payload.state || '0',
        payload.nullifierSeed,
        payload.signal,
      ];
    }

    try {
      const isValid = await snarkjs.groth16.verify(
        this.verificationKey,
        publicSignals,
        payload.groth16Proof
      );

      if (!isValid) {
        throw new AnonAadhaarProofTamperedError('snarkjs.groth16.verify returned false: invalid cryptographic proof');
      }
    } catch (err) {
      if (err instanceof AnonAadhaarProofTamperedError) {
        throw err;
      }
      throw new AnonAadhaarProofTamperedError(
        `Groth16 verification failed: ${err instanceof Error ? err.message : String(err)}`
      );
    }

    return {
      valid: true,
      mode: 'REAL_ANON_AADHAAR',
      identityNullifier: payload.nullifier,
      verifiedAt: Date.now(),
      metadata: {
        pubkeyHash: payload.pubkeyHash,
        timestamp: payload.timestamp,
        nullifierSeed: payload.nullifierSeed,
        signal: payload.signal,
      },
    };
  }
}
